export const IpcChannel = {
	macroList: "macro:list",
	macroGet: "macro:get",
	macroSave: "macro:save",
	macroDelete: "macro:delete",
	macroChanged: "macro:changed",
	settingsGet: "settings:get",
	settingsSet: "settings:set",
	recordStart: "record:start",
	recordStop: "record:stop",
	recordPauseToggle: "record:pause-toggle",
	recordState: "record:state",
	recordStopped: "record:stopped",
	playStart: "play:start",
	playStop: "play:stop",
	playState: "play:state",
	hotkeysSync: "hotkeys:sync",
	screenshotCapture: "screenshot:capture",
	screenshotCropSave: "screenshot:crop-save",
	captureGet: "capture:get",
	captureSave: "capture:save",
	captureChanged: "capture:changed",
	captureRun: "capture:run",
	captureStop: "capture:stop",
	captureState: "capture:state",
	captureScanPreview: "capture:scan-preview",
	// Canais por perfil: só existem enquanto a migração incremental não termina.
	captureProfileList: "capture:profile-list",
	captureProfileSave: "capture:profile-save",
	captureProfileDelete: "capture:profile-delete",
	captureProfilesChanged: "capture:profiles-changed",
	captureProfileRun: "capture:profile-run",
	captureProfileStop: "capture:profile-stop",
	captureProfileScanPreview: "capture:profile-scan-preview",
	dockToggle: "dock:toggle",
	windowRestoreMain: "window:restore-main",
} as const;
