// Nomes canônicos de tecla usados em toda a app (Steps, hotkeys, tecla de pânico).
// Mapeiam tanto para os keycodes do uiohook (gravação/hotkeys) quanto para o enum Key do nut.js (reprodução).
export const CANONICAL_KEYS = [
	"Ctrl",
	"Shift",
	"Alt",
	"Win",
	"Escape",
	"Enter",
	"Space",
	"Tab",
	"Backspace",
	"Delete",
	"Insert",
	"Home",
	"End",
	"PageUp",
	"PageDown",
	"ArrowUp",
	"ArrowDown",
	"ArrowLeft",
	"ArrowRight",
	"CapsLock",
	"0",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"A",
	"B",
	"C",
	"D",
	"E",
	"F",
	"G",
	"H",
	"I",
	"J",
	"K",
	"L",
	"M",
	"N",
	"O",
	"P",
	"Q",
	"R",
	"S",
	"T",
	"U",
	"V",
	"W",
	"X",
	"Y",
	"Z",
	"F1",
	"F2",
	"F3",
	"F4",
	"F5",
	"F6",
	"F7",
	"F8",
	"F9",
	"F10",
	"F11",
	"F12",
	"Semicolon",
	"Equal",
	"Comma",
	"Minus",
	"Period",
	"Slash",
	"Backquote",
	"BracketLeft",
	"Backslash",
	"BracketRight",
	"Quote",
	"Numpad0",
	"Numpad1",
	"Numpad2",
	"Numpad3",
	"Numpad4",
	"Numpad5",
	"Numpad6",
	"Numpad7",
	"Numpad8",
	"Numpad9",
	"NumpadAdd",
	"NumpadSubtract",
	"NumpadMultiply",
	"NumpadDivide",
	"NumpadDecimal",
] as const;

export type CanonicalKey = (typeof CANONICAL_KEYS)[number];

// keycode (uiohook, Windows) -> nome canônico
export const UIOHOOK_KEYCODE_TO_CANONICAL: Record<number, CanonicalKey> = {
	29: "Ctrl",
	3613: "Ctrl",
	42: "Shift",
	54: "Shift",
	56: "Alt",
	3640: "Alt",
	3675: "Win",
	3676: "Win",
	1: "Escape",
	28: "Enter",
	57: "Space",
	15: "Tab",
	14: "Backspace",
	3667: "Delete",
	3666: "Insert",
	3655: "Home",
	3663: "End",
	3657: "PageUp",
	3665: "PageDown",
	57416: "ArrowUp",
	57424: "ArrowDown",
	57419: "ArrowLeft",
	57421: "ArrowRight",
	58: "CapsLock",
	11: "0",
	2: "1",
	3: "2",
	4: "3",
	5: "4",
	6: "5",
	7: "6",
	8: "7",
	9: "8",
	10: "9",
	30: "A",
	48: "B",
	46: "C",
	32: "D",
	18: "E",
	33: "F",
	34: "G",
	35: "H",
	23: "I",
	36: "J",
	37: "K",
	38: "L",
	50: "M",
	49: "N",
	24: "O",
	25: "P",
	16: "Q",
	19: "R",
	31: "S",
	20: "T",
	22: "U",
	47: "V",
	17: "W",
	45: "X",
	21: "Y",
	44: "Z",
	59: "F1",
	60: "F2",
	61: "F3",
	62: "F4",
	63: "F5",
	64: "F6",
	65: "F7",
	66: "F8",
	67: "F9",
	68: "F10",
	87: "F11",
	88: "F12",
	39: "Semicolon",
	13: "Equal",
	51: "Comma",
	12: "Minus",
	52: "Period",
	53: "Slash",
	41: "Backquote",
	26: "BracketLeft",
	43: "Backslash",
	27: "BracketRight",
	40: "Quote",
	82: "Numpad0",
	79: "Numpad1",
	80: "Numpad2",
	81: "Numpad3",
	75: "Numpad4",
	76: "Numpad5",
	77: "Numpad6",
	71: "Numpad7",
	72: "Numpad8",
	73: "Numpad9",
	78: "NumpadAdd",
	74: "NumpadSubtract",
	55: "NumpadMultiply",
	3637: "NumpadDivide",
	83: "NumpadDecimal",
};

// Nomes canônicos que representam teclas modificadoras (não entram como "type" de texto solto)
export const MODIFIER_KEYS: ReadonlySet<CanonicalKey> = new Set(["Ctrl", "Shift", "Alt", "Win"]);

// Símbolo produzido por cada tecla de pontuação, sem/com Shift (layout US)
export const PUNCTUATION_CHAR: Partial<Record<CanonicalKey, { plain: string; shifted: string }>> = {
	Semicolon: { plain: ";", shifted: ":" },
	Equal: { plain: "=", shifted: "+" },
	Comma: { plain: ",", shifted: "<" },
	Minus: { plain: "-", shifted: "_" },
	Period: { plain: ".", shifted: ">" },
	Slash: { plain: "/", shifted: "?" },
	Backquote: { plain: "`", shifted: "~" },
	BracketLeft: { plain: "[", shifted: "{" },
	Backslash: { plain: "\\", shifted: "|" },
	BracketRight: { plain: "]", shifted: "}" },
	Quote: { plain: "'", shifted: '"' },
};
